spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost}

# Security 설정 (프로덕션)
security:
  cors:
    allowed-origins: ${SECURITY_CORS_ALLOWED_ORIGINS:${CORS_ALLOWED_ORIGINS:http://localhost}}
  jwt:
    private-key: ${JWT_PRIVATE_KEY}
    public-key: ${JWT_PUBLIC_KEY}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:1800000}
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}