spring:
  application:
    name: pullit-backend
    
  profiles:
    active: local
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        
  data:
    redis:
      timeout: 60000ms
      lettuce:
        pool:
          enabled: true
          max-active: 10
          max-idle: 10
          min-idle: 5
  cache:
    type: redis
    redis:
      time-to-live: 360000

server:
  port: 8080

cors:
  allowed-origins: http://localhost:5173,http://localhost:3000

# SpringDoc OpenAPI 설정
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha

# Security 설정
security:
  cors:
    allowed-origins:
      - http://localhost:5173
      - http://localhost:5174
      - http://localhost:3000
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers:
      - "*"
    allow-credentials: true
    max-age: 3600
  jwt:
    # 개발 환경용 RSA 키 (실제 운영에서는 파일 경로나 환경변수 사용)
    private-key: classpath:keys/private-key.pem
    public-key: classpath:keys/public-key.pem
  
logging:
  level:
    root: INFO
    com.pullit: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/pullit.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30