-- Add timestamp columns to calendar_events table
ALTER TABLE calendar_events 
ADD COLUMN created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;