name: Backend CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: pullit_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Create test RSA keys
      run: |
        mkdir -p src/main/resources/keys
        openssl genrsa -out src/main/resources/keys/private-key.pem 2048
        openssl rsa -in src/main/resources/keys/private-key.pem -pubout -out src/main/resources/keys/public-key.pem
    
    - name: Build with Gradle
      env:
        SPRING_PROFILES_ACTIVE: test
        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/pullit_test
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
        SPRING_REDIS_HOST: localhost
        SPRING_REDIS_PORT: 6379
        JWT_PRIVATE_KEY: classpath:keys/private-key.pem
        JWT_PUBLIC_KEY: classpath:keys/public-key.pem
      run: ./gradlew build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: jar-artifact
        path: build/libs/*.jar